/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 girlCat2.glb 
*/
import {useGLTF} from "@react-three/drei";
import {useGraph} from "@react-three/fiber";
import React from "react";

import {SkeletonUtils} from "three-stdlib";

export function GirlCat2(props) {
  const group = React.useRef();
  // const {nodes, materials} = useGLTF("/3dModels/girlCat2.glb");
  const {scene, animations} = useGLTF("/3dModels/girlCat2.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const {nodes, materials} = useGraph(clone);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <mesh
            geometry={nodes.heat.geometry}
            material={nodes.heat.material}
            position={[0, 1.325, 0]}
          />
          <mesh
            geometry={nodes.body.geometry}
            material={nodes.body.material}
            position={[0, 0.757, 0]}
            scale={0.201}
          />
          <mesh
            geometry={nodes.leg.geometry}
            material={nodes.leg.material}
            position={[0.093, 0.745, 0]}
            scale={[0.043, 0.047, 0.047]}
          />
          <mesh
            geometry={nodes.neck.geometry}
            material={nodes.neck.material}
            position={[0, 1.129, 0]}
            scale={0.052}
          />
          <mesh
            geometry={nodes.feet.geometry}
            material={nodes.feet.material}
            position={[0.098, 0.058, 0]}
            scale={0.058}
          />
          <mesh
            geometry={nodes.mandible.geometry}
            material={nodes.mandible.material}
            position={[0, 1.19, 0.072]}
            scale={[1, 1, 1.091]}
          />
          <mesh
            geometry={nodes.nose.geometry}
            material={nodes.nose.material}
            position={[0, 1.254, 0.319]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.035, 0.318, 0.035]}
          />
          <mesh
            geometry={nodes.mouth.geometry}
            material={nodes.mouth.material}
            position={[0.11, 1.194, 0.305]}
            rotation={[1.822, 0.394, -0.373]}
            scale={[0.015, 0.131, 0.015]}
          />
          <mesh
            geometry={nodes.eye.geometry}
            material={nodes.eye.material}
            position={[0.122, 1.338, 0.257]}
            rotation={[1.599, -0.038, 2.744]}
            scale={0.911}
          />
          <mesh
            geometry={nodes.pupil.geometry}
            material={nodes.pupil.material}
            position={[0.081, 1.339, 0.292]}
            rotation={[0.681, -1.202, -0.904]}
          />
          <mesh
            geometry={nodes.eyebrow.geometry}
            material={nodes.eyebrow.material}
            position={[0.061, 1.418, 0.302]}
            rotation={[0.681, -1.202, -0.904]}
          />
          <mesh
            geometry={nodes.heir.geometry}
            material={nodes.heir.material}
            position={[-0.078, 1.639, 0.113]}
            rotation={[0.836, -0.582, 0.546]}
          />
          <mesh
            geometry={nodes.heir001.geometry}
            material={nodes.heir001.material}
            position={[-0.079, 1.59, 0.157]}
            rotation={[1.293, -0.167, 0.767]}
          />
          <mesh
            geometry={nodes.heir002.geometry}
            material={nodes.heir002.material}
            position={[-0.048, 1.531, 0.157]}
            rotation={[1.524, -0.046, 0.775]}
          />
          <mesh
            geometry={nodes.coat.geometry}
            material={nodes.coat.material}
            position={[0, 0.757, 0]}
            scale={0.242}
          />
          <mesh
            geometry={nodes.Plane.geometry}
            material={nodes.Plane.material}
            position={[0, 0.889, 0]}
            scale={0.647}
          />
          <mesh
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[0.09, 0.578, 0]}
            scale={0.089}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dModels/girlCat2.gltf");
