/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 newX.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function NewX(props) {
  const { nodes, materials } = useGLTF('/3dModels/newX.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/3dModels/newX.glb')
