/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 untitled1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Untitled1(props) {
  const { nodes, materials } = useGLTF("/3dModels/untitled1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_75.geometry} material={materials.Blue} />
    </group>
  )
}

useGLTF.preload("/3dModels/untitled1.glb");
