/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Y2.glb 
*/
import {useGLTF} from "@react-three/drei";
import React from "react";

export function Y2(props) {
  const {nodes, materials} = useGLTF("/3dModels/Y2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/3dModels/Y2.glb");
