/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Y3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Y3(props) {
  const { nodes, materials } = useGLTF('/3dModels/Y3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/3dModels/Y3.glb')
