/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 yCorundum.glb 
*/
import {useGLTF} from "@react-three/drei";
import React from "react";

export function YCorundum(props) {
  const {nodes, materials} = useGLTF("/3dModels/yCorundum.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_78001.geometry}
        material={materials.Material}
        position={[0, 1.183, 0]}
        scale={0.455}
      />
    </group>
  );
}

useGLTF.preload("/3dModels/yCorundum.glb");
