/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 box.glb 
*/
import {useAnimations, useGLTF} from "@react-three/drei";
import {useGraph} from "@react-three/fiber";
import React, {useEffect} from "react";

import {useAppSelector} from "hooks/useReduxToolkit";
import {SkeletonUtils} from "three-stdlib";

export const Box = (props) => {
  const group = React.useRef();
  const {scene, animations} = useGLTF("/3dModels/box3.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const {nodes, materials} = useGraph(clone);
  const {actions, names} = useAnimations(animations, group);
  const {sideCube} = useAppSelector((state) => state.cubeBuilder);

  useEffect(() => {
    actions[names[0]]?.reset().fadeIn(0.5).play();

    return () => {
      actions[names[0]]?.reset().fadeOut(0.5);
    };
  }, [names, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.rootBone} />
      <skinnedMesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        skeleton={nodes.Cube.skeleton}
      />
      {sideCube && (
        <skinnedMesh
          geometry={nodes.SideCube.geometry}
          material={nodes.SideCube.material}
          skeleton={nodes.SideCube.skeleton}
        />
      )}
    </group>
  );
};

useGLTF.preload("/3dModels/box3.glb");
