/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 woman.gltf 
*/
import {useAnimations, useGLTF} from "@react-three/drei";
import {useGraph} from "@react-three/fiber";
import React from "react";

import {SkeletonUtils} from "three-stdlib";

export function Woman(props: any) {
  const group = React.useRef();
  const {scene, animations} = useGLTF("/3dModels/woman.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const {nodes, materials} = useGraph(clone);
  const {actions} = useAnimations(animations, group);
  // if (!nodes || !materials) return null;

  return (
    <group>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/3dModels/woman.gltf");
