/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 woman.gltf 
*/
import {useAnimations, useGLTF} from "@react-three/drei";
import {useGraph} from "@react-three/fiber";
import React, {useEffect} from "react";

import {useAppDispatch, useAppSelector} from "hooks/useReduxToolkit";
import {SkeletonUtils} from "three-stdlib";

import {setActions} from "../redux/slices/avatarActions";

export const Woman = (props) => {
  const group = React.useRef();
  const {scene, animations} = useGLTF("/3dModels/woman.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const {nodes, materials} = useGraph(clone);
  const {actions, names} = useAnimations(animations, group);
  const {currentAction} = useAppSelector((state) => state.avatarActions);
  const dispatch = useAppDispatch();
  useEffect(() => {
    actions[currentAction]?.reset().fadeIn(0.5).play();

    return () => {
      actions[currentAction]?.reset().fadeOut(0.5);
    };
  }, [currentAction, actions]);

  useEffect(() => {
    dispatch(setActions(names));
  }, [names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Hips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              name="Mesh019"
              geometry={nodes.Mesh019.geometry}
              material={materials.Glasses}
              skeleton={nodes.Mesh019.skeleton}
            />
            <skinnedMesh
              name="Mesh019_1"
              geometry={nodes.Mesh019_1.geometry}
              material={materials.Eyes}
              skeleton={nodes.Mesh019_1.skeleton}
            />
            <skinnedMesh
              name="Mesh019_2"
              geometry={nodes.Mesh019_2.geometry}
              material={materials.Hair}
              skeleton={nodes.Mesh019_2.skeleton}
            />
            <skinnedMesh
              name="Mesh019_3"
              geometry={nodes.Mesh019_3.geometry}
              material={materials.Skin}
              skeleton={nodes.Mesh019_3.skeleton}
            />
            <skinnedMesh
              name="Mesh019_4"
              geometry={nodes.Mesh019_4.geometry}
              material={materials.Mouth}
              skeleton={nodes.Mesh019_4.skeleton}
            />
            <skinnedMesh
              name="Mesh019_5"
              geometry={nodes.Mesh019_5.geometry}
              material={materials.Shirt}
              skeleton={nodes.Mesh019_5.skeleton}
            />
            <skinnedMesh
              name="Mesh019_6"
              geometry={nodes.Mesh019_6.geometry}
              material={materials.Pants}
              skeleton={nodes.Mesh019_6.skeleton}
            />
            <skinnedMesh
              name="Mesh019_7"
              geometry={nodes.Mesh019_7.geometry}
              material={materials.Shoes}
              skeleton={nodes.Mesh019_7.skeleton}
            />
            <skinnedMesh
              name="Mesh019_8"
              geometry={nodes.Mesh019_8.geometry}
              material={materials.Sole}
              skeleton={nodes.Mesh019_8.skeleton}
            />
            <skinnedMesh
              name="Mesh019_9"
              geometry={nodes.Mesh019_9.geometry}
              material={materials.Laces}
              skeleton={nodes.Mesh019_9.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/3dModels/woman.gltf");
